version: '3.8'
services:
  server:
    build:
      context: ./../../../../
      dockerfile: ./examples/web/https/simple-tls/server/Dockerfile
    environment:
      LOG_LABEL: HTTPS Server Example
    logging:
      driver: json-file
      options:
        max-size: 100m
  client:
    build:
      context: ./../../../../
      dockerfile: ./examples/web/https/simple-tls/client/Dockerfile
    environment:
      LOG_LABEL: Client Example
    depends_on:
        - server
    logging:
      driver: json-file
      options:
        max-size: 100m
