version: '3.8'
services:
  server:
    build:
      context: ./../../../
      dockerfile: ./examples/webUtils/framework/server/Dockerfile
    environment:
      LOG_LABEL: Express Framework Example
    logging:
      driver: json-file
      options:
        max-size: 100m
  client:
    build:
      context: ./../../../
      dockerfile: ./examples/webUtils/framework/client/Dockerfile
    environment:
      LOG_LABEL: Client Example
    depends_on:
        - server
    logging:
      driver: json-file
      options:
        max-size: 100m
