version: '3.8'
services:
  service-state-manager-sample-app:
    build:
      context: ./../../
      dockerfile: ./examples/serviceStateManager/Dockerfile
    ports:
      - 9000:9000
      - 8080:8080
    environment:
      ENABLE_EVENT_BASED_HEALTH_CHECK: "false"
    logging:
      driver: json-file
      options:
        max-size: 100m
    volumes:
      - ./app:/opt/example/app
