name: Microservice SDK - JS

# trigger when create a branch, push a tag or a branch, PR
on:
  create:
  push:
  pull_request:

jobs:
  unit-tests:
    name: 'Unit Tests'
    if: contains(github.event.head_commit.message, 'ci skip') == false # if the commit message has ci skip, doesn't run anything because needs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:

    - name: checkout
      uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm run lint
        npm test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: test/unit/coverage/lcov.info # create when run npm test
        flags: microserviceSdkJs # Flags allow you to isolate coverage reports for different tests
        name: microservice-sdk-js # Custom defined name for the upload
